[package]
authors = ["The Rust Project Developers"]
name = "core"
version = "0.0.0"
autotests = false
autobenches = false

[lib]
name = "core"
path = "lib.rs"
test = false
bench = false

[[test]]
name = "coretests"
path = "../libcore/tests/lib.rs"

[[bench]]
name = "corebenches"
path = "../libcore/benches/lib.rs"

[dev-dependencies]
<<<<<<< HEAD
rand = "0.5"
=======
rand = "0.5"
>>>>>>> ef3f51f65f30a5a8503ff4812e36de918ced03e7
